# fly.toml app configuration file generated for backend-quiz on 2024-03-25T12:13:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-quiz'
primary_region = 'sea'

[build]

[env]
  PORT = '3006'

[http_service]
  internal_port = 3006
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
